CREATE TABLE  recon_customers (
sequence_id SERIAL PRIMARY KEY,
recon_id varchar(100),
recon_status varchar(100),
identifiers_identifier_type_email varchar(100),
identifiers_identifier_type_username varchar(100),
identifiers_identifier_type_phone varchar(100),
customer_details_title varchar(100),
customer_details_first_name varchar(250),
customer_details_middle_name varchar(250),
customer_details_last_name varchar(250),
customer_details_dob varchar(250),
customer_details_gender varchar(250),
customer_details_nationality varchar(250),
customer_details_email_address varchar(256),
customer_details_mobile_phone_number varchar(250),
customer_details_home_phone_number varchar(250),
customer_details_business_phone_number varchar(250),
customer_details_contact_method varchar(250),
customer_details_country_of_residence varchar(250),
customer_details_country_of_taxation varchar(250),
customer_details_accessibility varchar(250),
customer_details_external_customer_id varchar(250),
additional_details_key varchar(250),
additional_details_value varchar(250),
next_page_token varchar(250),
previous_page_token varchar(250), 
recon_TM_load_timestamp timestamp default current_timestamp,
recon_load_TM_status varchar(250)
);