insert into plan(id ,
supervisor_contract_version_id ,
create_timestamp ,
status ,
opening_timestamp ,
activation_completed_timestamp ,
closing_timestamp  ,
closure_completed_timestamp ,
details_key ,
details_value ,
load_TM_status) select  "id","supervisor_contract_version_id" ,
                            "01/01/2999" ,
                            account_status ,
                            "01/01/2999" ,
                            "01/01/2999" ,
                            "01/01/2999"  ,
                            "01/01/2999" ,
                            "details_key" ,
                            "details_value" ,
                            load_TM_status from product_details;
                            commit;
